// DO NOT EDIT. This file is auto-generated by Payload.
// To regenerate, run `payload generate:importmap`
import { S3ClientUploadHandler as S3ClientUploadHandler_0 } from '@payloadcms/storage-s3/client'
import { RscEntryLexicalCell as RscEntryLexicalCell_1 } from '@payloadcms/richtext-lexical/rsc'
import { RscEntryLexicalField as RscEntryLexicalField_2 } from '@payloadcms/richtext-lexical/rsc'
import { InlineToolbarFeatureClient as InlineToolbarFeatureClient_3 } from '@payloadcms/richtext-lexical/client'
import { FixedToolbarFeatureClient as FixedToolbarFeatureClient_4 } from '@payloadcms/richtext-lexical/client'
import { HeadingFeatureClient as HeadingFeatureClient_5 } from '@payloadcms/richtext-lexical/client'
import { UnorderedListFeatureClient as UnorderedListFeatureClient_6 } from '@payloadcms/richtext-lexical/client'
import { OrderedListFeatureClient as OrderedListFeatureClient_7 } from '@payloadcms/richtext-lexical/client'
import { ChecklistFeatureClient as ChecklistFeatureClient_8 } from '@payloadcms/richtext-lexical/client'
import { LinkFeatureClient as LinkFeatureClient_9 } from '@payloadcms/richtext-lexical/client'
import { RelationshipFeatureClient as RelationshipFeatureClient_10 } from '@payloadcms/richtext-lexical/client'
import { BlockquoteFeatureClient as BlockquoteFeatureClient_11 } from '@payloadcms/richtext-lexical/client'
import { UploadFeatureClient as UploadFeatureClient_12 } from '@payloadcms/richtext-lexical/client'
import { BoldFeatureClient as BoldFeatureClient_13 } from '@payloadcms/richtext-lexical/client'
import { ItalicFeatureClient as ItalicFeatureClient_14 } from '@payloadcms/richtext-lexical/client'
import { UnderlineFeatureClient as UnderlineFeatureClient_15 } from '@payloadcms/richtext-lexical/client'
import { StrikethroughFeatureClient as StrikethroughFeatureClient_16 } from '@payloadcms/richtext-lexical/client'
import { SubscriptFeatureClient as SubscriptFeatureClient_17 } from '@payloadcms/richtext-lexical/client'
import { SuperscriptFeatureClient as SuperscriptFeatureClient_18 } from '@payloadcms/richtext-lexical/client'
import { InlineCodeFeatureClient as InlineCodeFeatureClient_19 } from '@payloadcms/richtext-lexical/client'
import { ParagraphFeatureClient as ParagraphFeatureClient_20 } from '@payloadcms/richtext-lexical/client'
import { AlignFeatureClient as AlignFeatureClient_21 } from '@payloadcms/richtext-lexical/client'
import { IndentFeatureClient as IndentFeatureClient_22 } from '@payloadcms/richtext-lexical/client'
import { HorizontalRuleFeatureClient as HorizontalRuleFeatureClient_23 } from '@payloadcms/richtext-lexical/client'
import { OverviewComponent as OverviewComponent_24 } from '@payloadcms/plugin-seo/client'
import { MetaTitleComponent as MetaTitleComponent_25 } from '@payloadcms/plugin-seo/client'
import { MetaDescriptionComponent as MetaDescriptionComponent_26 } from '@payloadcms/plugin-seo/client'
import { MetaImageComponent as MetaImageComponent_27 } from '@payloadcms/plugin-seo/client'
import { PreviewComponent as PreviewComponent_28 } from '@payloadcms/plugin-seo/client'

export const importMap = {
    '@payloadcms/storage-s3/client#S3ClientUploadHandler': S3ClientUploadHandler_0,
    '@payloadcms/richtext-lexical/rsc#RscEntryLexicalCell': RscEntryLexicalCell_1,
    '@payloadcms/richtext-lexical/rsc#RscEntryLexicalField': RscEntryLexicalField_2,
    '@payloadcms/richtext-lexical/client#InlineToolbarFeatureClient': InlineToolbarFeatureClient_3,
    '@payloadcms/richtext-lexical/client#FixedToolbarFeatureClient': FixedToolbarFeatureClient_4,
    '@payloadcms/richtext-lexical/client#HeadingFeatureClient': HeadingFeatureClient_5,
    '@payloadcms/richtext-lexical/client#UnorderedListFeatureClient': UnorderedListFeatureClient_6,
    '@payloadcms/richtext-lexical/client#OrderedListFeatureClient': OrderedListFeatureClient_7,
    '@payloadcms/richtext-lexical/client#ChecklistFeatureClient': ChecklistFeatureClient_8,
    '@payloadcms/richtext-lexical/client#LinkFeatureClient': LinkFeatureClient_9,
    '@payloadcms/richtext-lexical/client#RelationshipFeatureClient': RelationshipFeatureClient_10,
    '@payloadcms/richtext-lexical/client#BlockquoteFeatureClient': BlockquoteFeatureClient_11,
    '@payloadcms/richtext-lexical/client#UploadFeatureClient': UploadFeatureClient_12,
    '@payloadcms/richtext-lexical/client#BoldFeatureClient': BoldFeatureClient_13,
    '@payloadcms/richtext-lexical/client#ItalicFeatureClient': ItalicFeatureClient_14,
    '@payloadcms/richtext-lexical/client#UnderlineFeatureClient': UnderlineFeatureClient_15,
    '@payloadcms/richtext-lexical/client#StrikethroughFeatureClient': StrikethroughFeatureClient_16,
    '@payloadcms/richtext-lexical/client#SubscriptFeatureClient': SubscriptFeatureClient_17,
    '@payloadcms/richtext-lexical/client#SuperscriptFeatureClient': SuperscriptFeatureClient_18,
    '@payloadcms/richtext-lexical/client#InlineCodeFeatureClient': InlineCodeFeatureClient_19,
    '@payloadcms/richtext-lexical/client#ParagraphFeatureClient': ParagraphFeatureClient_20,
    '@payloadcms/richtext-lexical/client#AlignFeatureClient': AlignFeatureClient_21,
    '@payloadcms/richtext-lexical/client#IndentFeatureClient': IndentFeatureClient_22,
    '@payloadcms/richtext-lexical/client#HorizontalRuleFeatureClient': HorizontalRuleFeatureClient_23,
    '@payloadcms/plugin-seo/client#OverviewComponent': OverviewComponent_24,
    '@payloadcms/plugin-seo/client#MetaTitleComponent': MetaTitleComponent_25,
    '@payloadcms/plugin-seo/client#MetaDescriptionComponent': MetaDescriptionComponent_26,
    '@payloadcms/plugin-seo/client#MetaImageComponent': MetaImageComponent_27,
    '@payloadcms/plugin-seo/client#PreviewComponent': PreviewComponent_28,
}
